#!/usr/bin/env ruby

# rake => bundle exec rake
# test/* => bundle exec ruby -Itest
# spec/* => bundle exec rspec (or ruby?)

# examples:
# beer spec/models/user_spec.rb
# beer user_spec.rb
# beer user_spec.rb:123
# beer app/models/user.rb
# beer db:migrate # rake db:migrate
# beer s # rails s
# beer -T precompile
# beer cop user.rb
# beer head # rspec all modified local files
# beer master # rspec all files that are different from master

STDOUT.sync = true

class Beer
  attr_accessor :cmd, :args
  def initialize(args)
    @cmd = args.shift
    @args = args
  end

  def tweak
    tweak_cmd.tweak_args.tweak_env
  end

  def tweak_cmd
    @cmd ||= "rake"
    if cmd == "rake" || cmd == "ruby"
    elsif cmd == "gn" || cmd == "master"
      @cmd = "rspec"
      @args += `git diff upstream/master... --name-only`.chomp.split("\n")
    elsif cmd == "head"
      @cmd = "rspec"
      @args += `git diff HEAD --name-only`.chomp.split("\n")
    elsif cmd == "check"
      @cmd = "ruby"
      @args += ["-c"] +`git diff HEAD --name-only`.chomp.split("\n") +`git diff master --name-only`.chomp.split("\n")
    elsif cmd =~ /^(s|c|db|g|r|generate|server|console|dbconsole|runner)$/
      ENV["ERB_IN_CONFIG"]="true"
      ENV["SKIP_PRIMORDIAL_SEED"]="true" # OLD
      ENV["SKIP_SEEDING"]="true"
      ENV["RACK_MINI_PROFILER_PATCH"]="notifications" # miq_perf
      ENV["RAILS_SERVE_STATIC_FILES"]="true"
      ENV["DEBUG_ASSETS"]="true" # development.rb
      @args.unshift cmd
      @cmd = "rails"
    # elsif cmd =~ %r{^test/}
    #   args.unshift cmd
    #   cmd = "ruby -I test"
    elsif cmd =~ /^(cop|rubocop|rubo)$/
      @cmd = "rubocop"
    elsif cmd == "update"
      ENV["SKIP_TEST_RESET"]="1"
      ENV["SKIP_AUTOMATE_RESET"]="1"
      exec("./bin/update")
    elsif (cmd == "create" || cmd == "db:create") && args.empty?
      ENV["GOOD_MIGRATIONS"]="skip"
      @args = %w(db:create db:migrate db:seed) + @args
      @cmd = "rake"
    elsif (cmd == "migrate" || cmd == "db:migrate") && args.empty?
      @args = %w(db:migrate) + @args
      @cmd = "rake"
    # elsif cmd == "assets"
    #   bundle, bower, evm:assets:compile
    elsif cmd =~ %r{:[a-z]|-T}
      args.unshift cmd
      @cmd = "rake"
    elsif cmd =~ %r{(:?[^r]|^)(spec|app|db|lib)/} || cmd =~ /_spec.rb/
      args.unshift cmd
      @cmd = "rspec" # ruby -I rspec
    elsif cmd == "spec"
      @cmd = "rspec"
    elsif cmd == "check"
      @cmd = "ruby"
      @args = %w[-c] +`git diff HEAD --name-only`.chomp.split("\n")
    end

    self
  end

  def tweak_env
    ENV["RAILS_ENV"]="test" if @cmd == "rspec"

    self
  end

  def track_down(fn, lp = ':')
    fn, line = f_l(fn, lp)
    if !fn
      []
    elsif File.exists?(fn)
      [[fn, line].join]
    elsif !fn.include?('/')
      Dir.glob("**/#{fn}").select { |y| y.to_s !~ /factories\/|support\// }.map { |ref| "#{ref.to_s}#{line}" }
    else
      []
    end
  end

  def optionally_quote(phrase)
    if phrase.include?(" ")
      if phrase.include?('"')
        "'#{phrase}'"
      else
        "\"#{phrase}\""
      end
    else
      phrase
    end
  end

  def tweak_args
    if cmd == "rspec" || cmd == "subl"
      @args = args.flat_map do |x|
        # convert models to spec names
        # migrations have a slightly different name, fix that too

        # handle cases like --seed 10
        next(x) if x =~ /(-|\A\d+\Z)/
        x = x.sub("migrate", "migrations").gsub(%r{(?:./)?(?:app|db)/(.*).rb}) { "spec/#{$1}_spec.rb" }

        optionally_quote track_down(x).select {|f| f.include?("_spec.rb") }
      end
#    elsif cmd == "test"
#      @args = %w(-I test) + args.map { |x| x }
    elsif cmd == "rubocop"
      @args = args.flat_map { |x| track_down(x) }
    elsif cmd == "open"
      @args = args.flat_map { |x| track_down(x, '#L') } \
                  .flat_map { |f| `git url upstream/master "#{f}"`.strip }.compact
    end
    @args = @args.uniq
    self
  end

  def f_l(fn, lp = ':')
    if fn =~ /[\[\]:0-9]+$/
      _, fn, line = fn.match(/^(.*?)([:\[\]0-9]+)$/).to_a
      [fn, line.sub(':', lp)]
    else
      [fn, nil]
    end
  end

  def cmd_line
    %w(bundle exec) + [cmd] + args.map(&:to_s)
  end

  def print
    puts "#{cmd_line.join(" ")} ##{mug}#{mug}"
    self
  end

  def run
    exec(*cmd_line)
  end

  def mug
    "\xF0\x9F\x8D\xBA"
  end

  def self.run(args = ARGV)
    new(args).tweak.print.run
  end
end

Beer.run

