#!/usr/bin/env ruby

# determine project info

# create a change log template for the current project

require 'erb'

class Changelog
  def initialize
  end

  def create(filename = "CHANGELOG.md")
    File.write(filename, changelog_text)
  end

  def changelog_text
    url=base_url
    ERB.new(DATA.read).result(binding)
  end

  def tags
    # git_tags || sample_tags
    sample_tags
  end

  def url_for_tag(tag)
  end

  private

  # tags

  # tag => date
  # assumes recent ruby with ordered hashes
  def git_tags
    git("log --tags --simplify-by-decoration --pretty='format:%ai %d'")
    # TODO: fix
  end

  def sample_tags
    {
      "0.0.2" => Date.today.to_s,
      "0.0.1" => (Date.today - 4).to_s
    } # e.g.: "tag" => "2015-12-25"
  end

  # url

  def cur_branch
    git("symbolic-ref -q --short HEAD")
  end

  def cur_remote(branch = cur_branch)
    ret = git("config branch.#{branch}.remote")
    ret unless ret.empty?
  end

  # echo $(git remote-url $1) | sed -e 'sX^git@\([^:]*\):Xhttp://\1/X' -e 'sX\.git$XX')
  # @param remote_url [String] git@domain:user/repo.git
  # @return http://domain/user/repo/
  def base_url
    # can we leverage url for?
    remote = cur_remote || cur_remote("master") || "origin"
    remote_url = git("config --get remote.#{remote}.url") # TODO: pass in
    remote_url.gsub(%r{^git@([^:]*):}){"http://#{$1}/"}.gsub(/\.git$/,'')
  end

  # git goodness

  def git(*args)
    `git #{args.join(" ")}`.chomp
  end
end


changelog = Changelog.new

# if ARGV.size == 2
# else
# end

changelog.create
__END__
# Change Log
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/)
and this project adheres to [Semantic Versioning](http://semver.org/).

## [Unreleased]
### Added
- de translation from @mpbzh.

### Changed
- Start versioning based on the current English version at 0.0.2 to help
translation authors keep things up-to-date.

### Fixed

## [0.0.2] - #{today}
### Added
- RU translation from @aishek.
- pt-BR translation from @tallesl.
- es-ES translation from @ZeliosAriex.

## 0.0.1 - 2014-05-31
### Added
- good stuff

[Unreleased]: <%=url%>/compare/v0.0.2...HEAD
[0.0.2]: <%=url%>/compare/v0.0.1...v0.0.2
