#!/usr/bin/env bash

#command must be of the name dot2(format)

format=$(basename $0)
format=${format#*2}

if [ "$1" = "-o" ] ; then
  shift
  open="open"
else
  open="echo"
fi

for i in "$@" ; do
  target=${i%.*}.${format}
  dot -T$format $i -o ${target}
  $open ${target}
done
