#!/usr/bin/env bash

#command must be of the name dot2(format)

# bail on first error
set -e

format=$(basename $0)
# format: dot2svg:cairo => svg:cairo
format=${format#*2}
# extension: svg:cairo => svg
extension=${format%:*}

# -o will open the file
if [ "$1" = "-o" ] ; then
  shift
  open="open"
else
  open="echo"
fi

for i in "$@" ; do
  target=${i%.*}.${extension}
  dot -T$format $i -o ${target}
  ${open} ${target}
done
