#!/bin/bash

# usage git open [branch-name]

# directly taken from git aliases

## name of the current branch
function branch-name() {
  echo $(git symbolic-ref -q --short HEAD)
  echo "branch-name $(git symbolic-ref -q --short HEAD)" 1>&2
}

## remote branch this current branch is tracking
## e.g.:  origin
function remote-name() {
  echo $(git config branch.${1:-$(branch-name)}.remote)
  echo "remote-name $(git config branch.${1:-$(branch-name)}.remote)" 1>&2
}

## url for the current branch ($1 = name of remote) must be linked to master
## e.g.: git@github.com:user/prog.git
function remote-url() {
  echo $(git config remote.${1:-$(remote-name)}.url)
  echo "remote-url $(git config remote.${1:-$(remote-name)}.url)" 1>&2
}

  ## url at github ($1 = remote e.g.: origin) ($2 = tree compare) $3 = extra parameters
function hub-url() {
  # NOTE: in git aliases, back slashes double quoted
  hu="$(echo $(remote-url $1) | sed -e 'sX^git@\([^:]*\):Xhttp://\1/X' -e 'sX\.git$XX')"
  echo "${hu}/${2:-tree}/$(branch-name)${3:+?}${3}"
  echo "hub-url ${hu}/${2:-tree}/$(branch-name)${3:+?}${3}" 1>&2
}

## open-hub hub-url (origin tree compare)
function open-hub() {
  open $(hub-url ${1} ${2} ${3})
}

  ## open a pr
function pr() {
  #git push
  open-hub $(remote-name $1) compare expand=1
}

pr $1
