#!/usr/bin/env bash

# touch a gemfile, so the gemfile lock will be pegged to this file
root_dir=$(git rev-parse --show-toplevel)
branch="$(git symbolic-ref -q --short HEAD)"
ver_dir="${root_dir}/.ver"

version_gemfile="${ver_dir}/Gemfile.lock.${branch}"

if [ ! -f "${version_gemfile}" ] ; then
  echo "creating: ${ver_dir}/Gemfile.lock.${branch}"
  touch ${ver_dir}/Gemfile.lock.${branch}
  # create the symlink
  . $(git rev-parse --git-dir)/hooks/post-checkout
  echo "please run bundle"
fi

ret=$(git diff upstream/master -- Gemfile)
if [[ $( echo "${ret}" | wc -c) -eq 1 ]] ; then
  echo "note: gemfile matches upstream/master"
fi
