#!/usr/bin/env bash

# determines the database name from `git db`
#
# load database from backup
# if no database exists, create it first

function dbexists {
  [ "$( psql -XtAc "SELECT 1 FROM pg_database WHERE datname='$1'" )" = '1' ] && echo "true"
}


if [ $# -eq 1 ] ; then
    git db "${@}"
fi

DBNAME=$(git db -d)
PRIMARY_EXISTS=$(dbexists "${DBNAME}")
if [ -z "${PRIMARY_EXISTS}" ] ; then
  echo "Primary (${DBNAME}) does not exist (reason: ${PRIMARY_EXISTS}) "
  exit 1
fi

# if the database does not exist
BACKUP_EXISTS=$(dbexists "${DBNAME}_bak")
if [ -z "${BACKUP_EXISTS}" ] ; then
  echo "Creating backup"
  echo
  pcp ${DBNAME} ${DBNAME}_bak
else
  echo "restoring backup for ${DBNAME}"
  echo
  dropdb ${DBNAME} && pcp ${DBNAME}_bak ${DBNAME}
fi
