#!/usr/bin/env bash

# determines the database name from `git db`
#
# run once to back it up
# every time you run after that, it restores from backup (very quickly)

# alternative: pg_restore -j4 -v -d vmdb_development_hulk -v hulk-20230523.sql

function dbexists {
  [ "$( psql -XtAc "SELECT 1 FROM pg_database WHERE datname='$1'" )" = '1' ] && echo "true"
}

# I have this as a command. Put in here for other people
function pcp {
  local src=$1
  local dest=$2
  createdb -O ${PGUSER:-root} -T ${src} ${dest}
}

if [[ $USER = "kbrock" ]] ; do
  # kb workflow specific
  # set our rails app to use this database
  if [ $# -eq 1 ] ; then
    git db "${@}"
  fi
  DBNAME=$(git db -d 2> /dev/null)
else
  # normal people don't use git to store the database name.
  # So this is a normal/typical workflow
  DBNAME=${1-Require database name}
fi

# # fetch the database name from this rails app
PRIMARY_EXISTS=$(dbexists "${DBNAME}")
if [ -z "${PRIMARY_EXISTS}" ] ; then
  echo "Primary (${DBNAME}) does not exist (reason: ${PRIMARY_EXISTS}) "
  exit 1
fi

# if the database does not exist - create a backup
BACKUP_EXISTS=$(dbexists "${DBNAME}_bak")
if [ -z "${BACKUP_EXISTS}" ] ; then
  echo "Creating backup"
  echo
  pcp ${DBNAME} ${DBNAME}_bak
# if the database does exist - restore from backup
else
  echo "restoring backup for ${DBNAME}"
  echo
  dropdb ${DBNAME} && pcp ${DBNAME}_bak ${DBNAME}
fi
