#!/usr/bin/env bash

# references:
#   main: https://wiki.postgresql.org/wiki/Disk_Usage
#   alt:  http://www.postgresql.org/docs/9.0/static/disk-usage.html
function usage() {
  echo "usage: $(basename $0) [-h] [-v] [-l limit] [-r] [dbname] [tablename]" >&2
  echo "    shows disk usage for a database or all databases" >&2
  echo "    -h shows this help message" >&2
  echo "    -v vacuums the db first" >&2
  echo "    -l limits the results (default: 20)" >&2
  echo "    -r order by row count (default: size)" >&2
  echo "    -i include indexes (default: false)" >&2
  echo "    -c show commas" >&2
  echo "    -f show full info on tables" >&2
  echo "    -t include toasts" >&2
  echo "    -o order by column (default: 3 DESC / total size)" >&2
  exit 1
}

# defaulting limit to 20
limit=20
order="pg_relation_size(C.oid) DESC" # column 2 = disk usage
where=""
relkind="'r'"

while getopts "cfhil:rvto:" opt ; do
  case $opt in
    c) commas="\pset numericlocale" ;;
    h) usage ;;
    i) relkind="$relkind, 'i'" ;;
    l) limit=$OPTARG ;;
    t) relkind="$relkind, 't'" ;;
    r) order="reltuples DESC" ;;
    v) vacuum='vacuum full;' ;;
    f) full="true" ;;
    o) order=$OPTARG ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done
shift $((OPTIND-1))

# assuming PGUSER is set
dbname="$1"
export PGDATABASE="${dbname:-postgres}"

[[ -n "$full" ]] && relkind="'r'"
where="${where} AND relkind in ($relkind)"

if [ $# -gt 1 ] ; then # has tablename
  where="${where} AND relname like '%${2}%'"
  #order="${order}, relname"
fi

# which database is the biggest
if [ -z "${dbname}" ] ; then
  psql << SQL
    ${commas}
    ${vacuum}
    SELECT d.datname AS Name, pg_catalog.pg_get_userbyid(d.datdba) AS Owner,
        CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT')
            THEN pg_catalog.pg_size_pretty(pg_catalog.pg_database_size(d.datname))
            ELSE 'No Access'
        END AS Size
      FROM pg_catalog.pg_database d
      ORDER BY
        CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT')
            THEN pg_catalog.pg_database_size(d.datname)
            ELSE NULL
        END DESC -- nulls first
      LIMIT ${limit};
SQL
elif [ -n "${full}" ] ; then
  # full display, not just objects
  case $order in
    2) order="2 desc" ;;
    3) order="pg_total_relation_size(c.oid) desc" ;;
    4) order="pg_indexes_size(c.oid) desc" ;;
    5) order="pg_total_relation_size(reltoastrelid) desc nulls last" ;;
    6) order="pg_relation_size(c.oid) desc" ;;
  esac
  psql << SQL
    ${commas}
    ${vacuum}
    SELECT
          CASE WHEN nspname in ('public','pg_toast') THEN relname ELSE nspname || '.' || relname END AS "relation",
          reltuples::integer as "rows",
          pg_size_pretty(pg_total_relation_size(c.oid)) AS total,
          pg_size_pretty(pg_indexes_size(c.oid)) AS index,
          pg_size_pretty(pg_total_relation_size(reltoastrelid)) AS toast,
          pg_size_pretty(pg_relation_size(c.oid)) AS table
    FROM  pg_class c
     LEFT JOIN pg_namespace n ON (n.oid = c.relnamespace)
    WHERE nspname NOT IN ('pg_catalog', 'information_schema')
    ${where}
    ORDER BY ${order}
    LIMIT ${limit};
SQL
    # -- AND reltuples::integer > 0
    # -- ORDER BY pg_relation_size(C.oid) DESC;
else # which table objects are the biggest?
  psql << SQL
  ${commas}
  ${vacuum}
  SELECT
  relkind,
          CASE WHEN nspname in ('public','pg_toast') THEN relname ELSE nspname || '.' || relname END AS "relation",
          reltuples::integer as "rows",
          pg_size_pretty(pg_relation_size(c.oid)) AS "size"
    FROM  pg_class c
     LEFT JOIN pg_namespace n ON (n.oid = c.relnamespace)
    WHERE nspname NOT IN ('pg_catalog', 'information_schema')
    ${where}
    ORDER BY ${order}
    LIMIT ${limit};
SQL
fi
