#!/usr/bin/env bash

# processes running in a postgres server

if [ $# -eq 1 ] ; then
  limit="grep $1"
else
  #no limit
  limit='cat -'
fi

QUERY_COLUMN=current_query
QUERY_COLUMN=query
WAITING_COLUMN=waiting
WAITING_COLUMN=wait_event
psql -U postgres <<EOF | $limit
select datname, ${WAITING_COLUMN}, date_trunc('second',NOW()-query_start) as runtime, ${QUERY_COLUMN}
from pg_stat_activity where ${QUERY_COLUMN} <> '<IDLE>';
EOF

