#!/usr/bin/env bash

# processes running in a postgres server

if [ $# -eq 1 ] ; then
  limit="grep $1"
else
  #no limit
  limit='cat -'
fi

QUERY_COLUMN=current_query
QUERY_COLUMN=query

echo <<EOF | psql -U postgres | $limit 
select datname, waiting, date_trunc('second',NOW()-query_start) as runtime, ${QUERY_COLUMN}
from pg_stat_activity where ${QUERY_COLUMN} <> '<IDLE>';
EOF 

