#!/usr/bin/env bash

#? MiqMyServer.seed
# Zone.seed

# class MiqVimBrokerWorker::Runner
#   def heartbeat
#   end
# end

# row = MiqVimBrokerWorker.find_current || MiqVimBrokerWorker.create_worker_record
# guid = row.guid

# runner = MiqVimBrokerWorker::Runner.new(:guid => guid)
# runner.start

bundle exec ruby -Igems/pending/VMwareWebService/ gems/pending/VMwareWebService/test/MiqVimBrokerServer.rb

