#!/bin/sh

# connect to the vpn
# assumes the vpn is configured as the name PLM - set variable VPN_NAME if this is not the case

#environment variable VPN_NAME is the name in the vpn list of the vpn
vpn=${VPN_NAME:-PLM}
state=${1:-Please state on or off}

function silent_osa() {
  osascript -l AppleScript -e "${*:?need osa command}" > /dev/null
}

function vpn_was() {
  oldvalue=`osascript -l AppleScript -e "tell application \"System Events\" to tell current location of network preferences to return connected of current configuration of service \"${vpn}\""`

  case $oldvalue in
    on|true) echo "on" ;;
    off|false) echo "off" ;;
  esac
}

function turn_vpn() {
  case $1 in
    on|true) action="connect" ;;
    off|false) action="disconnect" ;;
    *)
      echo "unknown state $1"
      exit 1
      ;;
  esac
  silent_osa "tell application \"System Events\" to tell current location of network preferences to ${action} service \"${vpn}\""
}

#tell everyone else what the old value was
old=`vpn_was`

turn_vpn $state

# it takes a second to connect
# pause here - so it is easier to use as a companion script
if [ $old = 'off' ] ; then
  sleep 1
fi

# tell the old value of the vpn
# so scripts can 
echo $old